import 'package:freezed_annotation/freezed_annotation.dart';

part 'recommendation_direction.freezed.dart';
part 'recommendation_direction.g.dart';

/// Creative-layer recommendation generated by the LLM from market metrics.
/// Does NOT include technical parameters (Provider/Model, Voice Profile, etc.)
@freezed
abstract class RecommendationDirection with _$RecommendationDirection {
  const factory RecommendationDirection({
    required String suggestedTitle,
    required String synopsis,
    required List<String> genreTags,
    required int targetWordCount,
    required String marketHeatSummary,
    required String competitionSummary,
  }) = _RecommendationDirection;

  factory RecommendationDirection.fromJson(Map<String, Object?> json) =>
      _$RecommendationDirectionFromJson(json);
}
